dist: trusty
sudo: required
language: bash

stages:
  - name: Build and Release
    if: tag IS present

jobs:
  include:
    - stage: "Build and Release"
      name: "Build and release alfresco-keycloak-theme"
      before_deploy:
        - echo "Prepare deployment of alfresco-keycloak-theme-$TRAVIS_TAG"
        - ./build.sh
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: "alfresco-keycloak-theme-$TRAVIS_TAG.zip"
        skip_cleanup: true
        edge: true
        on:
          tags: true
          repo: Alfresco/alfresco-keycloak-theme